color:
  saturation: 0.1598663
  brandStrength: 0.9092063
  rhythmicContrast: 0.2219189
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  lightness: 0.929379
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.4525623
typography_spectrum: 0.1094145
name: Alan
